# Generated by Django 4.2.13 on 2024-05-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValuteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_code', models.CharField(max_length=15, verbose_name='Тикер')),
                ('name', models.CharField(max_length=100, verbose_name='Название валюты')),
            ],
        ),
        migrations.CreateModel(
            name='ValuteRateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата сбора данных')),
                ('value', models.FloatField(verbose_name='Курс')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valutes.valuteinfo', verbose_name='Валюта')),
            ],
        ),
    ]
